/**
 * Mock API data for development/demo mode.
 * Replace this file's exports with real API calls when the backend is ready.
 * The shape of each object matches the expected backend JSON contract.
 */

export const MOCK_ANALYSIS_RESULT = {
  session_id: "demo-session-001",
  application_type: "scholarship",
  status: "completed",
  readiness_score: 68,
  risk_level: "HIGH", // "LOW" | "MEDIUM" | "HIGH"
  overall_status: "FIX_REQUIRED", // "READY" | "FIX_REQUIRED"
  summary: {
    total_checks: 13,
    passed: 10,
    warnings: 1,
    critical: 2,
  },
  checks: [
    {
      id: "chk-001",
      category: "Identity",
      name: "DOB Consistency",
      status: "CRITICAL", // "PASS" | "WARNING" | "CRITICAL"
      description: "Date of birth does not match across documents.",
      documents_involved: ["Application Form", "Income Certificate"],
      values: {
        "Application Form": "14/03/2005",
        "Income Certificate": "14/03/2004",
      },
      why_it_matters:
        "Conflicting identity information may cause verification failure and application rejection.",
      recommendation:
        "Verify the correct date of birth and obtain a corrected Income Certificate.",
      evidence_ids: ["ev-001", "ev-002"],
    },
    {
      id: "chk-002",
      category: "Documents",
      name: "Caste Certificate",
      status: "CRITICAL",
      description: "Caste Certificate is missing from the uploaded documents.",
      documents_involved: [],
      values: {},
      why_it_matters:
        "The scholarship requires a valid Caste Certificate for OBC/SC/ST applicants.",
      recommendation: "Upload a valid Caste Certificate issued by a competent authority.",
      evidence_ids: [],
    },
    {
      id: "chk-003",
      category: "Photograph",
      name: "Photograph Dimensions",
      status: "WARNING",
      description: "Photograph exceeds the maximum allowed file size of 50 KB.",
      documents_involved: ["Photo.jpg"],
      values: {
        "Photo.jpg": "142 KB",
        "Required": "≤ 50 KB",
      },
      why_it_matters:
        "Oversized photographs may be rejected during online form submission.",
      recommendation: "Resize the photograph to under 50 KB using an image compression tool.",
      evidence_ids: ["ev-003"],
    },
    {
      id: "chk-004",
      category: "Identity",
      name: "Name Consistency — Application vs Aadhaar",
      status: "PASS",
      description: "Name matches across Application and Aadhaar.",
      documents_involved: ["Application Form", "Aadhaar.pdf"],
      values: {
        "Application Form": "Rahul Kumar Sharma",
        "Aadhaar.pdf": "Rahul Kumar Sharma",
      },
      why_it_matters: "Name must match across all identity documents.",
      recommendation: null,
      evidence_ids: ["ev-004", "ev-005"],
    },
    {
      id: "chk-005",
      category: "Identity",
      name: "DOB — Application vs Aadhaar",
      status: "PASS",
      description: "Date of birth matches between Application and Aadhaar.",
      documents_involved: ["Application Form", "Aadhaar.pdf"],
      values: {
        "Application Form": "14/03/2005",
        "Aadhaar.pdf": "14/03/2005",
      },
      why_it_matters: "Date of birth must be consistent across identity documents.",
      recommendation: null,
      evidence_ids: ["ev-001", "ev-006"],
    },
    {
      id: "chk-006",
      category: "Academic",
      name: "Marksheet — Minimum Percentage",
      status: "PASS",
      description: "Applicant meets the minimum percentage requirement.",
      documents_involved: ["Marksheet.pdf"],
      values: {
        "Marksheet.pdf": "87.4%",
        "Required": "≥ 75%",
      },
      why_it_matters: "Academic eligibility is a primary requirement.",
      recommendation: null,
      evidence_ids: ["ev-007"],
    },
    {
      id: "chk-007",
      category: "Financial",
      name: "Income Certificate — Annual Income",
      status: "PASS",
      description: "Annual income is within the permissible limit.",
      documents_involved: ["Income Certificate"],
      values: {
        "Income Certificate": "₹2,40,000 per annum",
        "Limit": "≤ ₹8,00,000",
      },
      why_it_matters: "Income threshold determines financial eligibility.",
      recommendation: null,
      evidence_ids: ["ev-008"],
    },
    {
      id: "chk-008",
      category: "Documents",
      name: "Application Form — Completeness",
      status: "PASS",
      description: "All mandatory fields in the application form are filled.",
      documents_involved: ["Application Form"],
      values: {},
      why_it_matters: "Incomplete forms are summarily rejected.",
      recommendation: null,
      evidence_ids: ["ev-009"],
    },
    {
      id: "chk-009",
      category: "Identity",
      name: "Name Consistency — Application vs Marksheet",
      status: "PASS",
      description: "Name matches between Application and Marksheet.",
      documents_involved: ["Application Form", "Marksheet.pdf"],
      values: {
        "Application Form": "Rahul Kumar Sharma",
        "Marksheet.pdf": "Rahul K. Sharma",
      },
      why_it_matters: "Minor variations in name can sometimes be flagged.",
      recommendation: null,
      evidence_ids: ["ev-010", "ev-011"],
    },
    {
      id: "chk-010",
      category: "Documents",
      name: "Photograph — Format",
      status: "PASS",
      description: "Photograph is in JPEG format as required.",
      documents_involved: ["Photo.jpg"],
      values: { "Photo.jpg": "JPEG" },
      why_it_matters: "Only JPEG/JPG photographs are accepted.",
      recommendation: null,
      evidence_ids: ["ev-003"],
    },
    {
      id: "chk-011",
      category: "Documents",
      name: "Signature Present",
      status: "PASS",
      description: "Applicant's signature is detected on the application form.",
      documents_involved: ["Application Form"],
      values: {},
      why_it_matters: "Unsigned applications are invalid.",
      recommendation: null,
      evidence_ids: ["ev-012"],
    },
    {
      id: "chk-012",
      category: "Financial",
      name: "Income Certificate — Authority",
      status: "PASS",
      description: "Income Certificate is issued by a recognised government authority.",
      documents_involved: ["Income Certificate"],
      values: {},
      why_it_matters: "Only certificates from authorised officers are accepted.",
      recommendation: null,
      evidence_ids: ["ev-008"],
    },
    {
      id: "chk-013",
      category: "Academic",
      name: "Marksheet — Year",
      status: "PASS",
      description: "Marksheet is from the current academic year as required.",
      documents_involved: ["Marksheet.pdf"],
      values: { "Year": "2024-25" },
      why_it_matters: "Outdated marksheets may not satisfy eligibility criteria.",
      recommendation: null,
      evidence_ids: ["ev-007"],
    },
  ],
  fix_plan: [
    {
      id: "fix-001",
      priority: 1,
      severity: "CRITICAL",
      check_id: "chk-001",
      action: "Fix DOB mismatch — obtain a corrected Income Certificate with the correct DOB (14/03/2005).",
      title: "Fix DOB Mismatch",
    },
    {
      id: "fix-002",
      priority: 2,
      severity: "CRITICAL",
      check_id: "chk-002",
      action: "Upload a valid Caste Certificate issued by a Tehsildar or District Magistrate.",
      title: "Upload Missing Caste Certificate",
    },
    {
      id: "fix-003",
      priority: 3,
      severity: "WARNING",
      check_id: "chk-003",
      action: "Resize photograph to under 50 KB. Use an online tool or image editor.",
      title: "Resize Photograph",
    },
  ],
  low_confidence_fields: [
    {
      id: "lcf-001",
      document: "Marksheet.pdf",
      field: "Applicant Name",
      extracted_value: "Rahul K. Sharma",
      confidence: 0.62,
      page: 1,
    },
  ],
  evidence: [
    {
      id: "ev-001",
      document: "Application Form",
      page: 1,
      field: "Date of Birth",
      value: "14/03/2005",
      confidence: 0.99,
    },
    {
      id: "ev-002",
      document: "Income Certificate",
      page: 1,
      field: "Date of Birth",
      value: "14/03/2004",
      confidence: 0.97,
    },
    {
      id: "ev-003",
      document: "Photo.jpg",
      page: 1,
      field: "File Size",
      value: "142 KB",
      confidence: 1.0,
    },
    {
      id: "ev-004",
      document: "Application Form",
      page: 1,
      field: "Applicant Name",
      value: "Rahul Kumar Sharma",
      confidence: 0.99,
    },
    {
      id: "ev-005",
      document: "Aadhaar.pdf",
      page: 1,
      field: "Name",
      value: "Rahul Kumar Sharma",
      confidence: 0.98,
    },
    {
      id: "ev-006",
      document: "Aadhaar.pdf",
      page: 1,
      field: "Date of Birth",
      value: "14/03/2005",
      confidence: 0.99,
    },
    {
      id: "ev-007",
      document: "Marksheet.pdf",
      page: 1,
      field: "Aggregate Percentage",
      value: "87.4%",
      confidence: 0.96,
    },
    {
      id: "ev-008",
      document: "Income Certificate",
      page: 1,
      field: "Annual Income",
      value: "₹2,40,000",
      confidence: 0.95,
    },
    {
      id: "ev-009",
      document: "Application Form",
      page: 1,
      field: "Completeness",
      value: "All fields filled",
      confidence: 0.98,
    },
    {
      id: "ev-010",
      document: "Application Form",
      page: 1,
      field: "Applicant Name",
      value: "Rahul Kumar Sharma",
      confidence: 0.99,
    },
    {
      id: "ev-011",
      document: "Marksheet.pdf",
      page: 1,
      field: "Student Name",
      value: "Rahul K. Sharma",
      confidence: 0.62,
    },
    {
      id: "ev-012",
      document: "Application Form",
      page: 2,
      field: "Signature",
      value: "Detected",
      confidence: 0.93,
    },
  ],
};

export const MOCK_READY_RESULT = {
  ...MOCK_ANALYSIS_RESULT,
  readiness_score: 100,
  risk_level: "LOW",
  overall_status: "READY",
  summary: {
    total_checks: 13,
    passed: 13,
    warnings: 0,
    critical: 0,
  },
  checks: MOCK_ANALYSIS_RESULT.checks.map((c) => ({ ...c, status: "PASS", recommendation: null })),
  fix_plan: [],
  low_confidence_fields: [],
};
